// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/batteries/register": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Atomic registration: descriptor + BMCS + BCF + initial health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "battery"
                ],
                "summary": "Register new battery with all static data",
                "parameters": [
                    {
                        "description": "Complete battery data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BatteryRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "BPAN generated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan_a}/carbon/compare/{bpan_b}": {
            "get": {
                "description": "Emission delta per stage, identify lower-emission battery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carbon"
                ],
                "summary": "Compare carbon footprints (A vs B)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "First BPAN",
                        "name": "bpan_a",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Second BPAN",
                        "name": "bpan_b",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Comparison result",
                        "schema": {
                            "$ref": "#/definitions/models.CarbonComparison"
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan}/carbon": {
            "get": {
                "description": "Retrieve BCF (all roles can view verified data)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carbon"
                ],
                "summary": "Get battery carbon footprint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Carbon footprint",
                        "schema": {
                            "$ref": "#/definitions/models.CarbonFootprintResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Submit BCF with raw material, manufacturing, transport, usage, recycling emissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carbon"
                ],
                "summary": "Submit battery carbon footprint (5-stage emissions)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Carbon data (5 stages)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CarbonFootprintRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Submission ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Unauthorized (non-manufacturer)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan}/carbon/verify": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Mark carbon data as verified against standard (ISO 14040, PEF, EU ETS)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "carbon"
                ],
                "summary": "Verify carbon footprint (third-party verifier only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Verification details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VerificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Verified",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Unauthorized (non-verifier)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan}/compliance": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Returns compliance status and violations for a battery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance"
                ],
                "summary": "Get battery compliance status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ComplianceStatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan}/health": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get current battery health status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthRecord"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Submit health update from BMS or manufacturer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Update battery health (SoH, cycles, degradation)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Health data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HealthUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Record ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan}/health/history": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get battery health time-series",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max records (default 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.HealthRecord"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan}/status": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update battery lifecycle status (service provider only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "battery"
                ],
                "summary": "Update battery status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan}/verify/operational": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Generates a ZK proof that battery meets operational standards (government/regulator only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance"
                ],
                "summary": "Verify battery operational compliance (ZK proof)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ComplianceProofResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/batteries/{bpan}/verify/second-life": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Generates a ZK proof that battery is eligible for second-life use (government/regulator only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance"
                ],
                "summary": "Verify second-life eligibility (ZK proof)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ComplianceProofResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/battery": {
            "get": {
                "description": "Retrieve battery information by BPAN query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "battery"
                ],
                "summary": "Get battery by query parameter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/circular-economy/batteries/{bpan}/recycle": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transitions state to RECYCLED (recycler only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "circular-economy"
                ],
                "summary": "Record battery recycling",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Recycling record payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RecyclingRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/circular-economy/batteries/{bpan}/reuse": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transitions state to SECOND_LIFE (reuse operator only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "circular-economy"
                ],
                "summary": "Certify battery for second-life reuse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reuse certification payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReuseCertificationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/circular-economy/dashboard": {
            "get": {
                "description": "Returns aggregated reuse and recycling metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "circular-economy"
                ],
                "summary": "Get circular economy metrics dashboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by manufacturer",
                        "name": "manufacturer_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by chemistry",
                        "name": "chemistry_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/compliance/scan": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Scans all batteries for compliance violations (regulator only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance"
                ],
                "summary": "Trigger compliance scan for all batteries",
                "responses": {
                    "202": {
                        "description": "Scan completed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden (non-regulator)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/compliance": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Returns aggregated compliance statistics (regulator/admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compliance"
                ],
                "summary": "Get compliance dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ComplianceDashboard"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/health/dashboard": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get battery health dashboard metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthDashboard"
                        }
                    }
                }
            }
        },
        "/api/v1/manufacturers": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "List all registered manufacturers (admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manufacturer"
                ],
                "summary": "List manufacturers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Register a new manufacturer (admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manufacturer"
                ],
                "summary": "Register manufacturer",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/public/battery/{bpan}": {
            "get": {
                "description": "Returns only public fields for a battery (no authentication required)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Get public battery information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BPAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Public battery data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Battery not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/public/qr/validate": {
            "post": {
                "description": "Validates a QR code payload for integrity (no authentication required)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Validate QR code payload",
                "parameters": [
                    {
                        "description": "QR payload to validate",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.QrValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Validation result",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Validation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Logs in a stakeholder and sets HttpOnly cookies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login stakeholder",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponseJSON"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Clears the authentication cookies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout stakeholder",
                "responses": {
                    "200": {
                        "description": "Logged out",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Uses the refresh token cookie to get a new access token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "responses": {
                    "200": {
                        "description": "Tokens refreshed",
                        "schema": {
                            "$ref": "#/definitions/models.RefreshResponseJSON"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing refresh token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Registers a new stakeholder with Email and Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new stakeholder",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterStakeholderPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful registration",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterStakeholderResponseJSON"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/batteries/scan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Decodes a QR code payload and returns battery information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "qr"
                ],
                "summary": "Scan and decode a QR code",
                "parameters": [
                    {
                        "description": "QR payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Validation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/material": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Get BMCS data for a battery (role-gated)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MaterialCompositionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Submit BMCS data for a battery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Material data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MaterialCompositionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SubmitMaterialResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/ownership/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the full chain of custody for a battery",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Get ownership history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/ownership/transfer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts a dual-party consent ownership transfer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Initiate battery ownership transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transfer payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TransferInitiateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/qr": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates a QR code PNG image containing the battery's BPAN payload",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "qr"
                ],
                "summary": "Generate QR code for a battery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "QR Code PNG image",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid BPAN",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "QR generation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/recycling": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transitions state to RECYCLED (recycler only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Record battery recycling",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/reuse": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transitions state to SECOND_LIFE (reuse operator only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Certify battery for second-life reuse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/telemetry": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the most recent telemetry readings for a battery",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get latest telemetry data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Battery not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uploads new telemetry readings from BMS/OEM (encrypted at rest)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Upload telemetry data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Telemetry data payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/telemetry/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns historical telemetry data for a battery",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get telemetry history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/transition": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Moves a battery through the FSM (e.g. OPERATIONAL → SECOND_LIFE)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Transition battery lifecycle state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transition payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TransitionStateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/verify/operational": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates a zero-knowledge proof that battery SoH meets threshold",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Verify battery is operational (ZK proof)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batteries/{bpan}/verify/signature": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Checks cryptographic integrity of all battery data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Verify battery data signature",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Battery PAN",
                        "name": "bpan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ownership/transfer/{id}/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Confirms a pending transfer (either party). Transfer completes when both confirm.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Confirm an ownership transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transfer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ownership/transfer/{id}/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Rejects a pending transfer (either party can reject)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lifecycle"
                ],
                "summary": "Reject an ownership transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transfer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rejection reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TransferRejectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.QrValidationRequest": {
            "type": "object",
            "properties": {
                "payload_json": {
                    "type": "string"
                }
            }
        },
        "models.BatteryDescriptorRequest": {
            "type": "object",
            "properties": {
                "capacity_kwh": {
                    "type": "number"
                },
                "cell_count": {
                    "type": "integer"
                },
                "cell_type": {
                    "type": "string"
                },
                "cell_voltage_nominal_v": {
                    "type": "number"
                },
                "chemistry_type": {
                    "type": "string"
                },
                "declared_cycle_life": {
                    "type": "integer"
                },
                "manufacture_date": {
                    "type": "string"
                },
                "manufacturer_id": {
                    "type": "string"
                },
                "manufacturing_country": {
                    "type": "string"
                },
                "manufacturing_facility": {
                    "type": "string"
                },
                "nominal_current_a": {
                    "type": "number"
                },
                "nominal_voltage_v": {
                    "type": "number"
                },
                "warranty_years": {
                    "type": "integer"
                }
            }
        },
        "models.BatteryRegistrationRequest": {
            "type": "object",
            "properties": {
                "carbon": {
                    "$ref": "#/definitions/models.CarbonFootprintRequest"
                },
                "descriptor": {
                    "$ref": "#/definitions/models.BatteryDescriptorRequest"
                },
                "health": {
                    "$ref": "#/definitions/models.HealthUpdateRequest"
                },
                "material": {
                    "$ref": "#/definitions/models.MaterialCompositionRequest"
                }
            }
        },
        "models.CarbonComparison": {
            "type": "object",
            "properties": {
                "bpan_a": {
                    "type": "string"
                },
                "bpan_a_lower": {
                    "type": "boolean"
                },
                "bpan_b": {
                    "type": "string"
                },
                "emissions_per_kwh_delta": {
                    "type": "number"
                },
                "stage1_delta": {
                    "type": "number"
                },
                "stage2_delta": {
                    "type": "number"
                },
                "stage3_delta": {
                    "type": "number"
                },
                "stage4_delta": {
                    "type": "number"
                },
                "stage5_delta": {
                    "type": "number"
                },
                "total_delta": {
                    "type": "number"
                }
            }
        },
        "models.CarbonFootprintRequest": {
            "type": "object",
            "properties": {
                "cell_production_method": {
                    "type": "string"
                },
                "factory_energy_source": {
                    "type": "string"
                },
                "manufacturing_emissions_kg_co2e": {
                    "type": "number"
                },
                "manufacturing_location": {
                    "type": "string"
                },
                "mining_method": {
                    "type": "string"
                },
                "raw_material_emissions_kg_co2e": {
                    "type": "number"
                },
                "raw_material_source_country": {
                    "type": "string"
                },
                "recycling_avoided_mining": {
                    "type": "number"
                },
                "recycling_emissions_kg_co2e": {
                    "type": "number"
                },
                "recycling_method": {
                    "type": "string"
                },
                "recycling_recovery_rate": {
                    "type": "number"
                },
                "transport_distance_km": {
                    "type": "number"
                },
                "transport_emissions_kg_co2e": {
                    "type": "number"
                },
                "transport_mode": {
                    "type": "string"
                },
                "transport_packaging": {
                    "type": "string"
                },
                "usage_annual_km": {
                    "type": "integer"
                },
                "usage_emissions_kg_co2e": {
                    "type": "number"
                },
                "usage_grid_emissions_factor_gco2e_per_kwh": {
                    "type": "number"
                },
                "usage_years": {
                    "type": "integer"
                }
            }
        },
        "models.CarbonFootprintResponse": {
            "type": "object",
            "properties": {
                "bpan": {
                    "type": "string"
                },
                "emissions_per_kwh": {
                    "type": "number"
                },
                "total_emissions_kg_co2e": {
                    "type": "number"
                },
                "verification_standard": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                },
                "verified_at": {
                    "type": "string"
                },
                "verified_by": {
                    "type": "string"
                }
            }
        },
        "models.ComplianceDashboard": {
            "type": "object",
            "properties": {
                "batteries_with_violations": {
                    "type": "integer"
                },
                "compliance_rate_percent": {
                    "type": "number"
                },
                "critical_violations": {
                    "type": "integer"
                },
                "last_scan_at": {
                    "type": "string"
                },
                "total_batteries": {
                    "type": "integer"
                },
                "violations_by_manufacturer": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "violations_by_type": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "warning_violations": {
                    "type": "integer"
                }
            }
        },
        "models.ComplianceProofResponse": {
            "type": "object",
            "properties": {
                "bpan": {
                    "type": "string"
                },
                "commitment": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "note": {
                    "type": "string"
                },
                "proof": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "requirement": {
                    "description": "\"operational\", \"second_life\", \"recyclable\"",
                    "type": "string"
                },
                "statement": {
                    "description": "Human-readable claim",
                    "type": "string"
                }
            }
        },
        "models.ComplianceStatusResponse": {
            "type": "object",
            "properties": {
                "bpan": {
                    "type": "string"
                },
                "critical_count": {
                    "type": "integer"
                },
                "last_checked_at": {
                    "type": "string"
                },
                "status": {
                    "description": "\"COMPLIANT\", \"WARNINGS_EXIST\", \"VIOLATIONS_EXIST\"",
                    "type": "string"
                },
                "violations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ComplianceViolation"
                    }
                },
                "warning_count": {
                    "type": "integer"
                }
            }
        },
        "models.ComplianceViolation": {
            "type": "object",
            "properties": {
                "action_deadline": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "detected_at": {
                    "type": "string"
                },
                "requires_action": {
                    "type": "boolean"
                },
                "severity": {
                    "description": "\"INFO\", \"WARNING\", \"CRITICAL\"",
                    "type": "string"
                },
                "violation_type": {
                    "type": "string"
                }
            }
        },
        "models.HealthDashboard": {
            "type": "object",
            "properties": {
                "avg_soh_by_chemistry": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float32"
                    }
                },
                "avg_soh_by_manufacturer": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float32"
                    }
                },
                "eol_count": {
                    "type": "integer"
                },
                "operational_count": {
                    "type": "integer"
                },
                "second_life_count": {
                    "type": "integer"
                },
                "waste_count": {
                    "type": "integer"
                }
            }
        },
        "models.HealthRecord": {
            "type": "object",
            "properties": {
                "average_temperature_celsius": {
                    "type": "number"
                },
                "bpan": {
                    "type": "string"
                },
                "cycle_count": {
                    "type": "integer"
                },
                "health_status": {
                    "description": "OPERATIONAL, SECOND_LIFE, etc.",
                    "type": "string"
                },
                "proofs_generated": {
                    "type": "boolean"
                },
                "reported_at": {
                    "type": "string"
                },
                "state_of_health_percent": {
                    "type": "number"
                }
            }
        },
        "models.HealthUpdateRequest": {
            "type": "object",
            "properties": {
                "average_temperature_celsius": {
                    "type": "number"
                },
                "cell_voltage_max_mv": {
                    "type": "number"
                },
                "cell_voltage_min_mv": {
                    "type": "number"
                },
                "cycle_count": {
                    "type": "integer"
                },
                "degradation_class": {
                    "type": "string"
                },
                "error_flags": {
                    "type": "string"
                },
                "internal_resistance_mohm": {
                    "type": "number"
                },
                "max_temperature_celsius": {
                    "type": "number"
                },
                "min_temperature_celsius": {
                    "type": "number"
                },
                "state_of_health_percent": {
                    "type": "number"
                }
            }
        },
        "models.LoginPayload": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "MySecureP@ssw0rd!"
                }
            }
        },
        "models.LoginResponseJSON": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Logged in successfully"
                },
                "role": {
                    "type": "string",
                    "example": "Government Authority"
                },
                "stakeholderId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "models.MaterialCompositionRequest": {
            "type": "object",
            "properties": {
                "anode_material": {
                    "type": "string",
                    "example": "Graphite"
                },
                "cadmium_content_g": {
                    "type": "number",
                    "example": 0
                },
                "cathode_material": {
                    "description": "Public fields",
                    "type": "string",
                    "example": "NMC811"
                },
                "cobalt_content_g": {
                    "type": "number",
                    "example": 120
                },
                "electrolyte_type": {
                    "type": "string",
                    "example": "LiPF6"
                },
                "hazardous_substances": {
                    "type": "string",
                    "example": "LiPF6"
                },
                "lead_content_g": {
                    "type": "number",
                    "example": 0
                },
                "lithium_content_g": {
                    "description": "Private fields (encrypted at Rust layer)",
                    "type": "number",
                    "example": 450
                },
                "manganese_content_g": {
                    "type": "number",
                    "example": 85
                },
                "nickel_content_g": {
                    "type": "number",
                    "example": 310
                },
                "recyclable_percentage": {
                    "type": "number",
                    "example": 92.5
                },
                "separator_material": {
                    "type": "string",
                    "example": "PE/PP"
                },
                "supply_chain_source": {
                    "type": "string",
                    "example": "Korea/Posco"
                }
            }
        },
        "models.MaterialCompositionResponse": {
            "type": "object",
            "properties": {
                "anode_material": {
                    "type": "string"
                },
                "bpan": {
                    "type": "string"
                },
                "cadmium_content_g": {
                    "type": "number"
                },
                "cathode_material": {
                    "type": "string"
                },
                "cobalt_content_g": {
                    "type": "number"
                },
                "electrolyte_type": {
                    "type": "string"
                },
                "hazardous_substances": {
                    "type": "string"
                },
                "lead_content_g": {
                    "type": "number"
                },
                "lithium_content_g": {
                    "description": "Private fields — populated only for authorised roles",
                    "type": "number"
                },
                "manganese_content_g": {
                    "type": "number"
                },
                "nickel_content_g": {
                    "type": "number"
                },
                "partial": {
                    "description": "true if private fields were redacted",
                    "type": "boolean"
                },
                "recyclable_percentage": {
                    "type": "number"
                },
                "separator_material": {
                    "type": "string"
                },
                "supply_chain_source": {
                    "type": "string"
                }
            }
        },
        "models.RecoveryRates": {
            "type": "object",
            "properties": {
                "cobalt_percent": {
                    "type": "number"
                },
                "lithium_percent": {
                    "type": "number"
                },
                "nickel_percent": {
                    "type": "number"
                },
                "other_percent": {
                    "type": "number"
                }
            }
        },
        "models.RecyclingRecordRequest": {
            "type": "object",
            "properties": {
                "method": {
                    "description": "\"hydrometallurgical\", \"pyrometallurgical\", \"mechanical\"",
                    "type": "string"
                },
                "recovery_rates": {
                    "$ref": "#/definitions/models.RecoveryRates"
                },
                "standard": {
                    "description": "\"ISO 14040\", \"R2C2\", etc.",
                    "type": "string"
                },
                "weight_kg": {
                    "type": "number"
                }
            }
        },
        "models.RefreshResponseJSON": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Token refreshed successfully"
                }
            }
        },
        "models.RegisterStakeholderPayload": {
            "type": "object",
            "properties": {
                "aadharDocumentBase64": {
                    "type": "string",
                    "example": "data:image/png;base64,iVBORw0KGgo..."
                },
                "aadharNumber": {
                    "type": "string",
                    "example": "123456789012"
                },
                "email": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "MySecureP@ssw0rd!"
                },
                "profileDetails": {
                    "type": "string",
                    "example": "{}"
                },
                "role": {
                    "type": "string",
                    "example": "Government Authority"
                }
            }
        },
        "models.RegisterStakeholderResponseJSON": {
            "type": "object",
            "properties": {
                "stakeholderId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "status": {
                    "type": "string",
                    "example": "SUCCESS"
                }
            }
        },
        "models.ReuseCertificationRequest": {
            "type": "object",
            "properties": {
                "application": {
                    "description": "\"stationary_storage\", \"grid_backup\", \"renewable_integration\"",
                    "type": "string"
                },
                "expected_years": {
                    "type": "integer"
                },
                "soh_percent": {
                    "type": "number"
                }
            }
        },
        "models.SubmitMaterialResponse": {
            "type": "object",
            "properties": {
                "data_hash": {
                    "type": "string"
                },
                "event_hash": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.TransferInitiateRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "to_owner_id": {
                    "type": "string"
                },
                "to_owner_role": {
                    "type": "string"
                }
            }
        },
        "models.TransferRejectRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "models.TransitionStateRequest": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "new_state": {
                    "type": "string"
                }
            }
        },
        "models.VerificationRequest": {
            "type": "object",
            "properties": {
                "standard": {
                    "description": "ISO 14040, PEF, EU ETS",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
