//! crypto.rs — gRPC service for encryption, signing, ZK proofs
//!
//! Stub implementation. Real logic wires in on Day 10 (HKDF), Day 12 (ZK), Day 13 (signing).

use tonic::{Request, Response, Status};

// Import generated protobuf types and service traits
// These are generated by tonic-build at compile time
pub mod crypto_proto {
    tonic::include_proto!("bpa.crypto.v1");
}

pub use crypto_proto::*;

// Import the service trait
pub use crypto_service_server::{CryptoService, CryptoServiceServer};

/// Empty implementation of CryptoService.
/// All methods return Status::UNIMPLEMENTED until concrete implementations are added.
pub struct CryptoServiceImpl;

#[tonic::async_trait]
impl CryptoService for CryptoServiceImpl {
    // Encryption RPCs
    async fn encrypt(
        &self,
        _request: Request<EncryptRequest>,
    ) -> Result<Response<EncryptResponse>, Status> {
        Err(Status::unimplemented("Encrypt not yet implemented"))
    }

    async fn decrypt(
        &self,
        _request: Request<DecryptRequest>,
    ) -> Result<Response<DecryptResponse>, Status> {
        Err(Status::unimplemented("Decrypt not yet implemented"))
    }

    // Signing RPCs
    async fn sign(
        &self,
        _request: Request<SignRequest>,
    ) -> Result<Response<SignResponse>, Status> {
        Err(Status::unimplemented("Sign not yet implemented"))
    }

    async fn verify(
        &self,
        _request: Request<VerifyRequest>,
    ) -> Result<Response<VerifyResponse>, Status> {
        Err(Status::unimplemented("Verify not yet implemented"))
    }

    async fn generate_key_pair(
        &self,
        _request: Request<GenerateKeyPairRequest>,
    ) -> Result<Response<GenerateKeyPairResponse>, Status> {
        Err(Status::unimplemented("GenerateKeyPair not yet implemented"))
    }

    // ZK proof RPCs
    async fn zk_prove(
        &self,
        _request: Request<ZkProveRequest>,
    ) -> Result<Response<ZkProveResponse>, Status> {
        Err(Status::unimplemented("ZkProve not yet implemented"))
    }

    async fn zk_verify(
        &self,
        _request: Request<ZkVerifyRequest>,
    ) -> Result<Response<ZkVerifyResponse>, Status> {
        Err(Status::unimplemented("ZkVerify not yet implemented"))
    }

    // Key management RPCs
    async fn rotate_dek(
        &self,
        _request: Request<RotateDekRequest>,
    ) -> Result<Response<RotateDekResponse>, Status> {
        Err(Status::unimplemented("RotateDek not yet implemented"))
    }
}
