// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: bpa.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterBatteryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ManufacturerId   string                 `protobuf:"bytes,1,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	ManufacturerCode string                 `protobuf:"bytes,2,opt,name=manufacturer_code,json=manufacturerCode,proto3" json:"manufacturer_code,omitempty"`
	ChemistryType    string                 `protobuf:"bytes,3,opt,name=chemistry_type,json=chemistryType,proto3" json:"chemistry_type,omitempty"`
	BatteryCategory  string                 `protobuf:"bytes,4,opt,name=battery_category,json=batteryCategory,proto3" json:"battery_category,omitempty"`
	ComplianceClass  string                 `protobuf:"bytes,5,opt,name=compliance_class,json=complianceClass,proto3" json:"compliance_class,omitempty"`
	NominalVoltage   float64                `protobuf:"fixed64,6,opt,name=nominal_voltage,json=nominalVoltage,proto3" json:"nominal_voltage,omitempty"`
	RatedCapacityKwh float64                `protobuf:"fixed64,7,opt,name=rated_capacity_kwh,json=ratedCapacityKwh,proto3" json:"rated_capacity_kwh,omitempty"`
	EnergyDensity    float64                `protobuf:"fixed64,8,opt,name=energy_density,json=energyDensity,proto3" json:"energy_density,omitempty"`
	WeightKg         float64                `protobuf:"fixed64,9,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	FormFactor       string                 `protobuf:"bytes,10,opt,name=form_factor,json=formFactor,proto3" json:"form_factor,omitempty"`
	SerialNumber     string                 `protobuf:"bytes,11,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	BatchNumber      string                 `protobuf:"bytes,12,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	FactoryCode      string                 `protobuf:"bytes,13,opt,name=factory_code,json=factoryCode,proto3" json:"factory_code,omitempty"`
	ProductionYear   uint32                 `protobuf:"varint,14,opt,name=production_year,json=productionYear,proto3" json:"production_year,omitempty"`
	SequenceNumber   string                 `protobuf:"bytes,15,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	ActorId          string                 `protobuf:"bytes,16,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterBatteryRequest) Reset() {
	*x = RegisterBatteryRequest{}
	mi := &file_bpa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBatteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBatteryRequest) ProtoMessage() {}

func (x *RegisterBatteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBatteryRequest.ProtoReflect.Descriptor instead.
func (*RegisterBatteryRequest) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterBatteryRequest) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *RegisterBatteryRequest) GetManufacturerCode() string {
	if x != nil {
		return x.ManufacturerCode
	}
	return ""
}

func (x *RegisterBatteryRequest) GetChemistryType() string {
	if x != nil {
		return x.ChemistryType
	}
	return ""
}

func (x *RegisterBatteryRequest) GetBatteryCategory() string {
	if x != nil {
		return x.BatteryCategory
	}
	return ""
}

func (x *RegisterBatteryRequest) GetComplianceClass() string {
	if x != nil {
		return x.ComplianceClass
	}
	return ""
}

func (x *RegisterBatteryRequest) GetNominalVoltage() float64 {
	if x != nil {
		return x.NominalVoltage
	}
	return 0
}

func (x *RegisterBatteryRequest) GetRatedCapacityKwh() float64 {
	if x != nil {
		return x.RatedCapacityKwh
	}
	return 0
}

func (x *RegisterBatteryRequest) GetEnergyDensity() float64 {
	if x != nil {
		return x.EnergyDensity
	}
	return 0
}

func (x *RegisterBatteryRequest) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *RegisterBatteryRequest) GetFormFactor() string {
	if x != nil {
		return x.FormFactor
	}
	return ""
}

func (x *RegisterBatteryRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RegisterBatteryRequest) GetBatchNumber() string {
	if x != nil {
		return x.BatchNumber
	}
	return ""
}

func (x *RegisterBatteryRequest) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

func (x *RegisterBatteryRequest) GetProductionYear() uint32 {
	if x != nil {
		return x.ProductionYear
	}
	return 0
}

func (x *RegisterBatteryRequest) GetSequenceNumber() string {
	if x != nil {
		return x.SequenceNumber
	}
	return ""
}

func (x *RegisterBatteryRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type RegisterBatteryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Bpan           string                 `protobuf:"bytes,1,opt,name=bpan,proto3" json:"bpan,omitempty"`
	StaticHash     string                 `protobuf:"bytes,2,opt,name=static_hash,json=staticHash,proto3" json:"static_hash,omitempty"`
	RegistrationId string                 `protobuf:"bytes,3,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterBatteryResponse) Reset() {
	*x = RegisterBatteryResponse{}
	mi := &file_bpa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBatteryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBatteryResponse) ProtoMessage() {}

func (x *RegisterBatteryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBatteryResponse.ProtoReflect.Descriptor instead.
func (*RegisterBatteryResponse) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterBatteryResponse) GetBpan() string {
	if x != nil {
		return x.Bpan
	}
	return ""
}

func (x *RegisterBatteryResponse) GetStaticHash() string {
	if x != nil {
		return x.StaticHash
	}
	return ""
}

func (x *RegisterBatteryResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *RegisterBatteryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetBatteryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bpan          string                 `protobuf:"bytes,1,opt,name=bpan,proto3" json:"bpan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatteryRequest) Reset() {
	*x = GetBatteryRequest{}
	mi := &file_bpa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatteryRequest) ProtoMessage() {}

func (x *GetBatteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatteryRequest.ProtoReflect.Descriptor instead.
func (*GetBatteryRequest) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatteryRequest) GetBpan() string {
	if x != nil {
		return x.Bpan
	}
	return ""
}

type GetBatteryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bpan          string                 `protobuf:"bytes,1,opt,name=bpan,proto3" json:"bpan,omitempty"`
	ChemistryType string                 `protobuf:"bytes,2,opt,name=chemistry_type,json=chemistryType,proto3" json:"chemistry_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatteryResponse) Reset() {
	*x = GetBatteryResponse{}
	mi := &file_bpa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatteryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatteryResponse) ProtoMessage() {}

func (x *GetBatteryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatteryResponse.ProtoReflect.Descriptor instead.
func (*GetBatteryResponse) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatteryResponse) GetBpan() string {
	if x != nil {
		return x.Bpan
	}
	return ""
}

func (x *GetBatteryResponse) GetChemistryType() string {
	if x != nil {
		return x.ChemistryType
	}
	return ""
}

func (x *GetBatteryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RegisterStakeholderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Email                string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	ProfileDetails       string                 `protobuf:"bytes,4,opt,name=profile_details,json=profileDetails,proto3" json:"profile_details,omitempty"`
	AadharNumber         string                 `protobuf:"bytes,5,opt,name=aadhar_number,json=aadharNumber,proto3" json:"aadhar_number,omitempty"`
	AadharDocumentBase64 string                 `protobuf:"bytes,6,opt,name=aadhar_document_base64,json=aadharDocumentBase64,proto3" json:"aadhar_document_base64,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterStakeholderRequest) Reset() {
	*x = RegisterStakeholderRequest{}
	mi := &file_bpa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStakeholderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStakeholderRequest) ProtoMessage() {}

func (x *RegisterStakeholderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStakeholderRequest.ProtoReflect.Descriptor instead.
func (*RegisterStakeholderRequest) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterStakeholderRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterStakeholderRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterStakeholderRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterStakeholderRequest) GetProfileDetails() string {
	if x != nil {
		return x.ProfileDetails
	}
	return ""
}

func (x *RegisterStakeholderRequest) GetAadharNumber() string {
	if x != nil {
		return x.AadharNumber
	}
	return ""
}

func (x *RegisterStakeholderRequest) GetAadharDocumentBase64() string {
	if x != nil {
		return x.AadharDocumentBase64
	}
	return ""
}

type RegisterStakeholderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StakeholderId string                 `protobuf:"bytes,1,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStakeholderResponse) Reset() {
	*x = RegisterStakeholderResponse{}
	mi := &file_bpa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStakeholderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStakeholderResponse) ProtoMessage() {}

func (x *RegisterStakeholderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStakeholderResponse.ProtoReflect.Descriptor instead.
func (*RegisterStakeholderResponse) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterStakeholderResponse) GetStakeholderId() string {
	if x != nil {
		return x.StakeholderId
	}
	return ""
}

func (x *RegisterStakeholderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_bpa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	StakeholderId string                 `protobuf:"bytes,3,opt,name=stakeholder_id,json=stakeholderId,proto3" json:"stakeholder_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_bpa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetStakeholderId() string {
	if x != nil {
		return x.StakeholderId
	}
	return ""
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_bpa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_bpa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_bpa_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_bpa_proto protoreflect.FileDescriptor

const file_bpa_proto_rawDesc = "" +
	"\n" +
	"\tbpa.proto\x12\x03bpa\"\xff\x04\n" +
	"\x16RegisterBatteryRequest\x12'\n" +
	"\x0fmanufacturer_id\x18\x01 \x01(\tR\x0emanufacturerId\x12+\n" +
	"\x11manufacturer_code\x18\x02 \x01(\tR\x10manufacturerCode\x12%\n" +
	"\x0echemistry_type\x18\x03 \x01(\tR\rchemistryType\x12)\n" +
	"\x10battery_category\x18\x04 \x01(\tR\x0fbatteryCategory\x12)\n" +
	"\x10compliance_class\x18\x05 \x01(\tR\x0fcomplianceClass\x12'\n" +
	"\x0fnominal_voltage\x18\x06 \x01(\x01R\x0enominalVoltage\x12,\n" +
	"\x12rated_capacity_kwh\x18\a \x01(\x01R\x10ratedCapacityKwh\x12%\n" +
	"\x0eenergy_density\x18\b \x01(\x01R\renergyDensity\x12\x1b\n" +
	"\tweight_kg\x18\t \x01(\x01R\bweightKg\x12\x1f\n" +
	"\vform_factor\x18\n" +
	" \x01(\tR\n" +
	"formFactor\x12#\n" +
	"\rserial_number\x18\v \x01(\tR\fserialNumber\x12!\n" +
	"\fbatch_number\x18\f \x01(\tR\vbatchNumber\x12!\n" +
	"\ffactory_code\x18\r \x01(\tR\vfactoryCode\x12'\n" +
	"\x0fproduction_year\x18\x0e \x01(\rR\x0eproductionYear\x12'\n" +
	"\x0fsequence_number\x18\x0f \x01(\tR\x0esequenceNumber\x12\x19\n" +
	"\bactor_id\x18\x10 \x01(\tR\aactorId\"\x8f\x01\n" +
	"\x17RegisterBatteryResponse\x12\x12\n" +
	"\x04bpan\x18\x01 \x01(\tR\x04bpan\x12\x1f\n" +
	"\vstatic_hash\x18\x02 \x01(\tR\n" +
	"staticHash\x12'\n" +
	"\x0fregistration_id\x18\x03 \x01(\tR\x0eregistrationId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"'\n" +
	"\x11GetBatteryRequest\x12\x12\n" +
	"\x04bpan\x18\x01 \x01(\tR\x04bpan\"g\n" +
	"\x12GetBatteryResponse\x12\x12\n" +
	"\x04bpan\x18\x01 \x01(\tR\x04bpan\x12%\n" +
	"\x0echemistry_type\x18\x02 \x01(\tR\rchemistryType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xe6\x01\n" +
	"\x1aRegisterStakeholderRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12'\n" +
	"\x0fprofile_details\x18\x04 \x01(\tR\x0eprofileDetails\x12#\n" +
	"\raadhar_number\x18\x05 \x01(\tR\faadharNumber\x124\n" +
	"\x16aadhar_document_base64\x18\x06 \x01(\tR\x14aadharDocumentBase64\"\\\n" +
	"\x1bRegisterStakeholderResponse\x12%\n" +
	"\x0estakeholder_id\x18\x01 \x01(\tR\rstakeholderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x92\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12%\n" +
	"\x0estakeholder_id\x18\x03 \x01(\tR\rstakeholderId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"Y\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken2\x99\x01\n" +
	"\n" +
	"BpaService\x12L\n" +
	"\x0fRegisterBattery\x12\x1b.bpa.RegisterBatteryRequest\x1a\x1c.bpa.RegisterBatteryResponse\x12=\n" +
	"\n" +
	"GetBattery\x12\x16.bpa.GetBatteryRequest\x1a\x17.bpa.GetBatteryResponse2\xcd\x01\n" +
	"\vAuthService\x12X\n" +
	"\x13RegisterStakeholder\x12\x1f.bpa.RegisterStakeholderRequest\x1a .bpa.RegisterStakeholderResponse\x12.\n" +
	"\x05Login\x12\x11.bpa.LoginRequest\x1a\x12.bpa.LoginResponse\x124\n" +
	"\aRefresh\x12\x13.bpa.RefreshRequest\x1a\x14.bpa.RefreshResponseB\bZ\x06api/pbb\x06proto3"

var (
	file_bpa_proto_rawDescOnce sync.Once
	file_bpa_proto_rawDescData []byte
)

func file_bpa_proto_rawDescGZIP() []byte {
	file_bpa_proto_rawDescOnce.Do(func() {
		file_bpa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bpa_proto_rawDesc), len(file_bpa_proto_rawDesc)))
	})
	return file_bpa_proto_rawDescData
}

var file_bpa_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bpa_proto_goTypes = []any{
	(*RegisterBatteryRequest)(nil),      // 0: bpa.RegisterBatteryRequest
	(*RegisterBatteryResponse)(nil),     // 1: bpa.RegisterBatteryResponse
	(*GetBatteryRequest)(nil),           // 2: bpa.GetBatteryRequest
	(*GetBatteryResponse)(nil),          // 3: bpa.GetBatteryResponse
	(*RegisterStakeholderRequest)(nil),  // 4: bpa.RegisterStakeholderRequest
	(*RegisterStakeholderResponse)(nil), // 5: bpa.RegisterStakeholderResponse
	(*LoginRequest)(nil),                // 6: bpa.LoginRequest
	(*LoginResponse)(nil),               // 7: bpa.LoginResponse
	(*RefreshRequest)(nil),              // 8: bpa.RefreshRequest
	(*RefreshResponse)(nil),             // 9: bpa.RefreshResponse
}
var file_bpa_proto_depIdxs = []int32{
	0, // 0: bpa.BpaService.RegisterBattery:input_type -> bpa.RegisterBatteryRequest
	2, // 1: bpa.BpaService.GetBattery:input_type -> bpa.GetBatteryRequest
	4, // 2: bpa.AuthService.RegisterStakeholder:input_type -> bpa.RegisterStakeholderRequest
	6, // 3: bpa.AuthService.Login:input_type -> bpa.LoginRequest
	8, // 4: bpa.AuthService.Refresh:input_type -> bpa.RefreshRequest
	1, // 5: bpa.BpaService.RegisterBattery:output_type -> bpa.RegisterBatteryResponse
	3, // 6: bpa.BpaService.GetBattery:output_type -> bpa.GetBatteryResponse
	5, // 7: bpa.AuthService.RegisterStakeholder:output_type -> bpa.RegisterStakeholderResponse
	7, // 8: bpa.AuthService.Login:output_type -> bpa.LoginResponse
	9, // 9: bpa.AuthService.Refresh:output_type -> bpa.RefreshResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bpa_proto_init() }
func file_bpa_proto_init() {
	if File_bpa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bpa_proto_rawDesc), len(file_bpa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bpa_proto_goTypes,
		DependencyIndexes: file_bpa_proto_depIdxs,
		MessageInfos:      file_bpa_proto_msgTypes,
	}.Build()
	File_bpa_proto = out.File
	file_bpa_proto_goTypes = nil
	file_bpa_proto_depIdxs = nil
}
