// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: bpa.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BpaService_RegisterBattery_FullMethodName = "/bpa.BpaService/RegisterBattery"
	BpaService_GetBattery_FullMethodName      = "/bpa.BpaService/GetBattery"
)

// BpaServiceClient is the client API for BpaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BpaServiceClient interface {
	RegisterBattery(ctx context.Context, in *RegisterBatteryRequest, opts ...grpc.CallOption) (*RegisterBatteryResponse, error)
	GetBattery(ctx context.Context, in *GetBatteryRequest, opts ...grpc.CallOption) (*GetBatteryResponse, error)
}

type bpaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBpaServiceClient(cc grpc.ClientConnInterface) BpaServiceClient {
	return &bpaServiceClient{cc}
}

func (c *bpaServiceClient) RegisterBattery(ctx context.Context, in *RegisterBatteryRequest, opts ...grpc.CallOption) (*RegisterBatteryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBatteryResponse)
	err := c.cc.Invoke(ctx, BpaService_RegisterBattery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpaServiceClient) GetBattery(ctx context.Context, in *GetBatteryRequest, opts ...grpc.CallOption) (*GetBatteryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatteryResponse)
	err := c.cc.Invoke(ctx, BpaService_GetBattery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BpaServiceServer is the server API for BpaService service.
// All implementations must embed UnimplementedBpaServiceServer
// for forward compatibility.
type BpaServiceServer interface {
	RegisterBattery(context.Context, *RegisterBatteryRequest) (*RegisterBatteryResponse, error)
	GetBattery(context.Context, *GetBatteryRequest) (*GetBatteryResponse, error)
	mustEmbedUnimplementedBpaServiceServer()
}

// UnimplementedBpaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBpaServiceServer struct{}

func (UnimplementedBpaServiceServer) RegisterBattery(context.Context, *RegisterBatteryRequest) (*RegisterBatteryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBattery not implemented")
}
func (UnimplementedBpaServiceServer) GetBattery(context.Context, *GetBatteryRequest) (*GetBatteryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBattery not implemented")
}
func (UnimplementedBpaServiceServer) mustEmbedUnimplementedBpaServiceServer() {}
func (UnimplementedBpaServiceServer) testEmbeddedByValue()                    {}

// UnsafeBpaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BpaServiceServer will
// result in compilation errors.
type UnsafeBpaServiceServer interface {
	mustEmbedUnimplementedBpaServiceServer()
}

func RegisterBpaServiceServer(s grpc.ServiceRegistrar, srv BpaServiceServer) {
	// If the following call panics, it indicates UnimplementedBpaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BpaService_ServiceDesc, srv)
}

func _BpaService_RegisterBattery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBatteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpaServiceServer).RegisterBattery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpaService_RegisterBattery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpaServiceServer).RegisterBattery(ctx, req.(*RegisterBatteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpaService_GetBattery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpaServiceServer).GetBattery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpaService_GetBattery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpaServiceServer).GetBattery(ctx, req.(*GetBatteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BpaService_ServiceDesc is the grpc.ServiceDesc for BpaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BpaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bpa.BpaService",
	HandlerType: (*BpaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBattery",
			Handler:    _BpaService_RegisterBattery_Handler,
		},
		{
			MethodName: "GetBattery",
			Handler:    _BpaService_GetBattery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bpa.proto",
}

const (
	AuthService_RegisterStakeholder_FullMethodName = "/bpa.AuthService/RegisterStakeholder"
	AuthService_Login_FullMethodName               = "/bpa.AuthService/Login"
	AuthService_Refresh_FullMethodName             = "/bpa.AuthService/Refresh"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	RegisterStakeholder(ctx context.Context, in *RegisterStakeholderRequest, opts ...grpc.CallOption) (*RegisterStakeholderResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) RegisterStakeholder(ctx context.Context, in *RegisterStakeholderRequest, opts ...grpc.CallOption) (*RegisterStakeholderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterStakeholderResponse)
	err := c.cc.Invoke(ctx, AuthService_RegisterStakeholder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, AuthService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	RegisterStakeholder(context.Context, *RegisterStakeholderRequest) (*RegisterStakeholderResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) RegisterStakeholder(context.Context, *RegisterStakeholderRequest) (*RegisterStakeholderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterStakeholder not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_RegisterStakeholder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStakeholderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterStakeholder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterStakeholder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterStakeholder(ctx, req.(*RegisterStakeholderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bpa.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterStakeholder",
			Handler:    _AuthService_RegisterStakeholder_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _AuthService_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bpa.proto",
}
