// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: rides.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZkProof       string                 `protobuf:"bytes,1,opt,name=zkProof,proto3" json:"zkProof,omitempty"`
	RideDetails   string                 `protobuf:"bytes,2,opt,name=rideDetails,proto3" json:"rideDetails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRideRequest) Reset() {
	*x = CreateRideRequest{}
	mi := &file_rides_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideRequest) ProtoMessage() {}

func (x *CreateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideRequest.ProtoReflect.Descriptor instead.
func (*CreateRideRequest) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRideRequest) GetZkProof() string {
	if x != nil {
		return x.ZkProof
	}
	return ""
}

func (x *CreateRideRequest) GetRideDetails() string {
	if x != nil {
		return x.RideDetails
	}
	return ""
}

type RideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ZkProof       string                 `protobuf:"bytes,2,opt,name=zkProof,proto3" json:"zkProof,omitempty"`
	RideDetails   string                 `protobuf:"bytes,3,opt,name=rideDetails,proto3" json:"rideDetails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RideResponse) Reset() {
	*x = RideResponse{}
	mi := &file_rides_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideResponse) ProtoMessage() {}

func (x *RideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideResponse.ProtoReflect.Descriptor instead.
func (*RideResponse) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{1}
}

func (x *RideResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RideResponse) GetZkProof() string {
	if x != nil {
		return x.ZkProof
	}
	return ""
}

func (x *RideResponse) GetRideDetails() string {
	if x != nil {
		return x.RideDetails
	}
	return ""
}

type GetRidesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRidesRequest) Reset() {
	*x = GetRidesRequest{}
	mi := &file_rides_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRidesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRidesRequest) ProtoMessage() {}

func (x *GetRidesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRidesRequest.ProtoReflect.Descriptor instead.
func (*GetRidesRequest) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{2}
}

type GetRidesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rides         []*RideResponse        `protobuf:"bytes,1,rep,name=rides,proto3" json:"rides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRidesResponse) Reset() {
	*x = GetRidesResponse{}
	mi := &file_rides_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRidesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRidesResponse) ProtoMessage() {}

func (x *GetRidesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRidesResponse.ProtoReflect.Descriptor instead.
func (*GetRidesResponse) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{3}
}

func (x *GetRidesResponse) GetRides() []*RideResponse {
	if x != nil {
		return x.Rides
	}
	return nil
}

var File_rides_proto protoreflect.FileDescriptor

const file_rides_proto_rawDesc = "" +
	"\n" +
	"\vrides.proto\x12\x05rides\"O\n" +
	"\x11CreateRideRequest\x12\x18\n" +
	"\azkProof\x18\x01 \x01(\tR\azkProof\x12 \n" +
	"\vrideDetails\x18\x02 \x01(\tR\vrideDetails\"Z\n" +
	"\fRideResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\azkProof\x18\x02 \x01(\tR\azkProof\x12 \n" +
	"\vrideDetails\x18\x03 \x01(\tR\vrideDetails\"\x11\n" +
	"\x0fGetRidesRequest\"=\n" +
	"\x10GetRidesResponse\x12)\n" +
	"\x05rides\x18\x01 \x03(\v2\x13.rides.RideResponseR\x05rides2\x87\x01\n" +
	"\vRideService\x12;\n" +
	"\n" +
	"CreateRide\x12\x18.rides.CreateRideRequest\x1a\x13.rides.RideResponse\x12;\n" +
	"\bGetRides\x12\x16.rides.GetRidesRequest\x1a\x17.rides.GetRidesResponseB\bZ\x06api/pbb\x06proto3"

var (
	file_rides_proto_rawDescOnce sync.Once
	file_rides_proto_rawDescData []byte
)

func file_rides_proto_rawDescGZIP() []byte {
	file_rides_proto_rawDescOnce.Do(func() {
		file_rides_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rides_proto_rawDesc), len(file_rides_proto_rawDesc)))
	})
	return file_rides_proto_rawDescData
}

var file_rides_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rides_proto_goTypes = []any{
	(*CreateRideRequest)(nil), // 0: rides.CreateRideRequest
	(*RideResponse)(nil),      // 1: rides.RideResponse
	(*GetRidesRequest)(nil),   // 2: rides.GetRidesRequest
	(*GetRidesResponse)(nil),  // 3: rides.GetRidesResponse
}
var file_rides_proto_depIdxs = []int32{
	1, // 0: rides.GetRidesResponse.rides:type_name -> rides.RideResponse
	0, // 1: rides.RideService.CreateRide:input_type -> rides.CreateRideRequest
	2, // 2: rides.RideService.GetRides:input_type -> rides.GetRidesRequest
	1, // 3: rides.RideService.CreateRide:output_type -> rides.RideResponse
	3, // 4: rides.RideService.GetRides:output_type -> rides.GetRidesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rides_proto_init() }
func file_rides_proto_init() {
	if File_rides_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rides_proto_rawDesc), len(file_rides_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rides_proto_goTypes,
		DependencyIndexes: file_rides_proto_depIdxs,
		MessageInfos:      file_rides_proto_msgTypes,
	}.Build()
	File_rides_proto = out.File
	file_rides_proto_goTypes = nil
	file_rides_proto_depIdxs = nil
}
